spring.application.name=cb-search-service


server.port=7001
elastic.required.field.search.json.path=/EsFieldsmapping/trendingSearchEsMapping.json


elasticsearch.host=localhost
elasticsearch.port=9201
elasticsearch.username=
elasticsearch.password=

spring.cassandra.startupTimeoutInSeconds=100000
spring.cassandra.contact-points=localhost
spring.cassandra.port=9042
spring.cassandra.keyspace-name=sunbird
spring.cassandra.username=sunbird
spring.cassandra.password=""
spring.cassandra.local-datacenter=DC1
sunbird_cassandra_consistency_level=ONE

cassandra.config.host=localhost


sso.url=https://portal.dev.karmayogibharat.net/auth/
sso.realm=sunbird
sso.connection.pool.size=20
sso.enabled=true

accesstoken.publickey.basepath=publickey